######################## default configuration ####################
baseURL = "http://examplesite.org/"
title = "Bigspring Light"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

primary_font = "Montserrat:wght@200;300"
primary_font_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"