#################### default parameters ################################
favicon = "favicon.png"
logo = "images/logo-hexagonal.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "roadmap"
link = "sistemas"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "Github"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/salsa-community"

[[social]]
title = "Discourse"
icon = "fab fa-discourse" # themify icon : https://themify.me/themify-icons
link = "https://forum.crip.conacyt.mx/"

[[social]]
title = "Rocketchat"
icon = "fab fa-rocketchat" # themify icon : https://themify.me/themify-icons
link = "https://chat.crip.conacyt.mx/channel/Salsa/"
